[workspace]
members = [
    "sylphie",
    "sylphie_commands",
    "sylphie_core",
    "sylphie_database",
    "sylphie_derive",
    "sylphie_utils",
]

[profile.release]
opt-level = 3
debug = 1
lto = true
