[package]
name = "sylphie_mod_discord"
version = "0.1.0"
authors = ["Lymia Aluysia <lymia@lymiahugs.com>"]
edition = "2018"

[features]

[dependencies]
minnie = { version = "0.1.0", path = "../../minnie/minnie" }
sylphie = { version = "0.1.0", path = "../sylphie/sylphie" }